apiVersion: batch/v1
kind: CronJob
metadata:
  name: s6rasheedat-db-restore
spec:
  schedule: "* * * * *"  # Run the job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: s6rasheedat-db-restore
            image: rasheedata/restore:v7.0.0  # Replace with your Docker image name and tag
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: s6rasheedat-db-restore
            - configMapRef:
                name: s6rasheedat-db-restore
          restartPolicy: OnFailure
          # volumes:
          # - name: backup-volume
          #   persistentVolumeClaim:
          #     claimName: your-pvc-name  # Replace with your PersistentVolumeClaim name
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1